# Generated by Django 4.1.2 on 2022-10-31 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image8',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
