# Generated by Django 4.1.2 on 2022-10-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_delete_multipleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='blogpost',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ManyToManyField(blank=True, to='blog.image'),
        ),
    ]
