# Generated by Django 4.1.2 on 2022-10-31 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_image_blogpost_blogpost_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='blogpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
    ]
