# Generated by Django 4.1.2 on 2022-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_like_count_blogpost_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
